Updated.

diff --git a/bin/proofgeneral b/bin/proofgeneral
--- a/bin/proofgeneral
+++ b/bin/proofgeneral
@@ -3,7 +3,6 @@
 # Simple shell script for launching Proof General.
 #
 # Set EMACS to override choice of Emacs version
-# (otherwise script chooses emacs in preference to xemacs)
 #
 # PGHOME must be set to the directory where the lisp files of
 # Proof General are installed.  Script checks standard locations
@@ -20,15 +19,6 @@
 # or unpack Proof General in your home directory.
 # NB: no trailing backslash here!
 PGHOMEDEFAULT=$HOME/ProofGeneral
-
-# Try to find a default Emacs executable 
-if [ -z "$EMACS" ] || [ ! -x "$EMACS" ]; then
-    if which emacs > /dev/null; then 
-	EMACS=`which emacs`
-    else 
-	EMACS=`which xemacs`
-    fi
-fi
 
 # Try to find Proof General directory
 if [ -d $PGHOMEDEFAULT ]; then
@@ -47,8 +37,6 @@ HELP="Usage: proofgeneral [OPTION] [FILE]...
 Launches Emacs Proof General, editing the proof script FILE.
 
 Options:
-  --emacs	      startup Proof General with emacs (GNU Emacs)
-  --xemacs            startup Proof General with xemacs (XEmacs)
   --emacsbin <EMACS>  startup Proof General with emacs binary <EMACS>
   -h, --help          show this help and exit
   -v, --version       output version information and exit
@@ -65,7 +53,7 @@ Report bugs at http://proofgeneral.inf.ed.ac.uk/trac"
 
 VERSIONBLURB='David Aspinall.
 
-Copyright (C) 1998-2005 LFCS, University of Edinburgh, UK.
+Copyright (C) 1998-2008 LFCS, University of Edinburgh, UK.
 This is free software; see the source for copying conditions.'
 
    
@@ -87,10 +75,6 @@ while
 	echo "$NAME" "($VERSION)"
 	echo "$VERSIONBLURB"
 	exit 0;;
-    --emacs)
-	EMACS=`which emacs`;;
-    --xemacs)
-	EMACS=`which xemacs`;;
     --emacsbin)
 	EMACS=$2
 	shift;;
@@ -99,7 +83,7 @@ while
 do shift; done
 
 if [ ! -x "$EMACS" ]; then
-    echo "$NAME: cannot find an Emacs or XEmacs executable.  Set EMACS or your PATH." 1>&2
+    echo "$NAME: cannot find an Emacs executable.  Edit this script or your PATH." 1>&2
     exit 1
 fi
 
